(() => {
  const cfg=window.STADIUM_SYNC_CONFIG||{};
  const ready=cfg.supabaseUrl&&cfg.supabaseAnonKey&&window.supabase;
  const client=ready?window.supabase.createClient(cfg.supabaseUrl,cfg.supabaseAnonKey):null;
  let user=null,timer=null,busy=false;
  const $=s=>document.querySelector(s);
  const status=(text,kind='')=>{const el=$('#syncStatus');if(el){el.textContent=text;el.className=kind;}};
  const setUi=()=>{const connected=!!user;$('#syncAuthFields')?.toggleAttribute('hidden',connected);$('#syncConnectedFields')?.toggleAttribute('hidden',!connected);if(!ready)status('Cloud sync is not configured yet. Open SETUP-CLOUD-SYNC.md in the ZIP.','error');else if(user)status(`Connected as ${user.email}.`, 'ok');else status('Not signed in. Your information is still stored safely on this device.');};
  async function mediaPayload(){if(typeof allPhotos!=='function')return {};return await allPhotos();}
  function localTime(){return localStorage.getItem('stadiumPassportLocalUpdatedAt')||'';}
  async function localPayload(){return {version:3,updatedAt:localTime()||new Date().toISOString(),state:window.state||state,photos:await mediaPayload()};}
  async function upload(){if(!client||!user)throw new Error('Sign in first.');const payload=await localPayload();const {error}=await client.from('passport_snapshots').upsert({user_id:user.id,payload,device_updated_at:payload.updatedAt},{onConflict:'user_id'});if(error)throw error;localStorage.setItem('stadiumPassportCloudUpdatedAt',payload.updatedAt);status('This device was uploaded to the cloud.','ok');return payload;}
  async function remote(){const {data,error}=await client.from('passport_snapshots').select('payload,device_updated_at,updated_at').eq('user_id',user.id).maybeSingle();if(error)throw error;return data;}
  async function apply(payload){if(!payload)return;Object.keys(state).forEach(k=>delete state[k]);Object.assign(state,payload.state||{});localStorage.setItem('stadiumPassportState',JSON.stringify(state));for(const [id,p] of Object.entries(payload.photos||{}))await putPhotos(id,Array.isArray(p)?p:[p]);localStorage.setItem('stadiumPassportLocalUpdatedAt',payload.updatedAt||new Date().toISOString());localStorage.setItem('stadiumPassportCloudUpdatedAt',payload.updatedAt||'');render();}
  async function download(){if(!client||!user)throw new Error('Sign in first.');const row=await remote();if(!row?.payload)throw new Error('No cloud copy exists yet.');await apply(row.payload);status('Cloud data was downloaded to this device.','ok');}
  async function checkRefreshRequests(){if(!client||!user)return;const last=localStorage.getItem('stadiumPassportLastRefreshRequest')||'1970-01-01T00:00:00Z';const {data,error}=await client.from('schedule_refresh_requests').select('*').gt('created_at',last).order('created_at',{ascending:true});if(error)throw error;if(!data?.length)return;for(const request of data){const prefix='stadiumPassportScheduleV22_2:';for(let i=localStorage.length-1;i>=0;i--){const key=localStorage.key(i);if(key?.startsWith(prefix))localStorage.removeItem(key);}localStorage.setItem('stadiumPassportLastRefreshRequest',request.created_at);}status(`Schedule refresh received for ${data[data.length-1].league} ${data[data.length-1].season}. Open that team's season to load the newest calendar.`,'ok');}
  async function sync({force}={}){if(busy||!client||!user)return;busy=true;try{status('Syncing…');const row=await remote();const lt=localTime();const rt=row?.payload?.updatedAt||row?.device_updated_at||'';if(force==='upload'||!row?.payload||lt>rt)await upload();else if(force==='download'||rt>lt)await apply(row.payload);await checkRefreshRequests();status('Sync complete.','ok');}catch(e){console.error(e);status(e.message||'Sync failed.','error');throw e;}finally{busy=false;}}
  function scheduleSync(){if(!cfg.autoSync||!user)return;clearTimeout(timer);timer=setTimeout(()=>sync().catch(()=>{}),cfg.autoSyncDelayMs||2500);}
  async function signIn(){const email=$('#syncEmail').value.trim(),password=$('#syncPassword').value;const {data,error}=await client.auth.signInWithPassword({email,password});if(error)throw error;user=data.user;setUi();await sync();}
  async function signUp(){const email=$('#syncEmail').value.trim(),password=$('#syncPassword').value;const {data,error}=await client.auth.signUp({email,password});if(error)throw error;user=data.user;setUi();status(data.session?'Account created and signed in.':'Account created. Check your email to confirm, then sign in.','ok');if(data.session)await upload();}
  async function signOut(){await client.auth.signOut();user=null;setUi();}
  function bind(){setUi();$('#syncSignIn')?.addEventListener('click',()=>signIn().catch(e=>status(e.message,'error')));$('#syncSignUp')?.addEventListener('click',()=>signUp().catch(e=>status(e.message,'error')));$('#syncNow')?.addEventListener('click',()=>sync().catch(()=>{}));$('#syncUpload')?.addEventListener('click',()=>sync({force:'upload'}).catch(()=>{}));$('#syncDownload')?.addEventListener('click',()=>{if(confirm('Replace this device data with the cloud copy?'))sync({force:'download'}).catch(()=>{});});$('#syncSignOut')?.addEventListener('click',()=>signOut().catch(e=>status(e.message,'error')));}
  window.StadiumCloud={scheduleSync,sync,upload,download};
  document.addEventListener('DOMContentLoaded',async()=>{bind();if(!client)return;const {data}=await client.auth.getSession();user=data.session?.user||null;setUi();if(user)sync().catch(()=>{});client.auth.onAuthStateChange((_event,session)=>{user=session?.user||null;setUi();});});
})();
