create table if not exists public.passport_snapshots (
  user_id uuid primary key references auth.users(id) on delete cascade,
  payload jsonb not null default '{}'::jsonb,
  device_updated_at timestamptz,
  updated_at timestamptz not null default now()
);

create table if not exists public.schedule_refresh_requests (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  league text not null check (league in ('NFL','CFB','MLB','CBB','NBA')),
  season integer not null,
  created_at timestamptz not null default now()
);

alter table public.passport_snapshots enable row level security;
alter table public.schedule_refresh_requests enable row level security;
create policy "own snapshot select" on public.passport_snapshots for select using (auth.uid()=user_id);
create policy "own snapshot insert" on public.passport_snapshots for insert with check (auth.uid()=user_id);
create policy "own snapshot update" on public.passport_snapshots for update using (auth.uid()=user_id);
create policy "own refresh select" on public.schedule_refresh_requests for select using (auth.uid()=user_id);
create policy "own refresh insert" on public.schedule_refresh_requests for insert with check (auth.uid()=user_id);
